server:     true
safe:       false
auto:       true

url:        http://localhost:4000
#baseurl:    /journal
permalink:  /:year-:month-:day/:title

source:      .
destination: ./_site
plugins:     ./_plugins

markdown:   textile
pygments:   true

stylus:
  compress: true
  path: ./pub/css