server:     true
auto:       true

url:        http://localhost:4000
baseurl:    /journal
permalink:  /:title

source:      .
destination: ./_site
plugins:     ./_plugins

markdown:   textile
pygments:   true